GlucoGroove/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('blood_sugars/', include('blood_sugars.urls')),
]

# if settings.DEBUG: 
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path
from .views import home_page, blog_detail, register, login_view, upvote_post, downvote_post, upvote_comment, downvote_comment, edit_post, delete_post, edit_comment, delete_comment, create_post, custom_password_reset, custom_password_reset_confirm, about
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Home page view
    path('', home_page, name='home_page'),

    # About page
    path('about/', about, name='about'),

    # User authentication views
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),  # Use custom login view
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Custom password reset views
    path('password_reset/', custom_password_reset, name='custom_password_reset'),
    path('password_reset/confirm/', custom_password_reset_confirm, name='custom_password_reset_confirm'),

    # Blog post detail view
    path('post/<slug:slug>/', blog_detail, name='blog_detail'),

    # Voting functionalities for posts and comments
    path('blog/post/<int:post_id>/upvote/', upvote_post, name='upvote_post'),
    path('blog/post/<int:post_id>/downvote/', downvote_post, name='downvote_post'),
    path('blog/comment/<int:comment_id>/upvote/', upvote_comment, name='upvote_comment'),
    path('blog/comment/<int:comment_id>/downvote/', downvote_comment, name='downvote_comment'),

    # Create Post
    path('create/', create_post, name='create_post'),

    # Edit and delete post views
    path('post/<int:post_id>/edit/', edit_post, name='edit_post'),
    path('post/<int:post_id>/delete/', delete_post, name='delete_post'),

    # Edit and delete comment views
    path('comment/<int:comment_id>/edit/', edit_comment, name='edit_comment'),
    path('comment/<int:comment_id>/delete/', delete_comment, name='delete_comment'),
]

blood_sugars/urls.py
from django.urls import path
from .views import blood_sugar_tracker, food_diary, daily_diary, fetch_glucose_data
from .import views
app_name = 'blood_sugars'

urlpatterns = [
    path('blood-sugar-tracker/', views.blood_sugar_tracker, name='blood_sugar_tracker'),
    path('food_diary/', food_diary, name='food_diary'),
    path('daily_diary/', daily_diary, name='daily_diary'),
    path('fetch_glucose_data/', fetch_glucose_data, name='fetch_glucose_data'),
]

templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>About GlucoGroove</h1>
    <p>GlucoGroove is dedicated to helping you manage your diabetes effectively and efficiently.
        Our tools allow you to track your blood sugar levels, monitor your carbohydrate intake, and manage your insulin doses all in one place.</p>
    <p>Our mission is to make diabetes management simpler and more intuitive, empowering you to take control of your health.</p>
    <p>In addition to our robust tracking tools, GlucoGroove features a dynamic blog where users can share their experiences, insights, and tips.
        We believe in fostering a supportive community where individuals can learn from one another, exchange stories, and build connections.</p>

    <h2>Our Story</h2>
    <p>Founded by individuals who understand the challenges of living with diabetes,
        GlucoGroove aims to provide comprehensive and user-friendly solutions for all your diabetes management needs.
        Our community-driven approach ensures that everyone feels heard and supported.
        We are passionate about making a positive impact on the lives of those living with diabetes
        and are committed to continuous improvement and innovation.
    </p>


</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100" lang="en">
<head>
<title>GlucoGroove</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description"
    content="Use our blood sugar tracker to monitor and manage your diabetes. Track sugar levels, carbohydrates, and insulin doses easily.">
    <meta name="keywords"
    content="blood sugar tracker, glucogroove, GlucoGroove, diabetes tracker, diabetes management, blood sugar levels, track blood sugar, insulin tracking, carbohydrate tracker, diabetes app, health tracking, blood sugar control, diabetic health, diabetes monitor">
    <meta name="robots" content="index, follow">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'site.webmanifest' %}">
    <link rel="icon" href="{% static 'favicon.ico' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="d-flex flex-column h-100">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <!-- Logo -->
            <a class="navbar-brand d-flex align-items-center" href="{% url 'home_page' %}">
                <img src="{% static 'images/GlucoGroove_logo.jpg' %}" alt="GlucoGroove Logo" class="logo me-2">
                <strong class="glucogroove">GlucoGroove</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == home_url %}active{% endif %}" href="{% url 'home_page' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Trackers
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'blood_sugars:blood_sugar_tracker' %}">Blood Sugar Tracker</a></li>
                            <li><a class="dropdown-item" href="{% url 'blood_sugars:food_diary' %}">Food Diary</a></li>
                            <li><a class="dropdown-item" href="{% url 'blood_sugars:daily_diary' %}">Daily Diary</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create_post' %}">Create Blog Post</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav align-items-center">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text me-2">You are logged in as {{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/register/' %}active{% endif %}" href="{% url 'register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/login/' %}active{% endif %}" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <span class="navbar-text me-2">You are not logged in</span>
                    </li>
                    {% endif %}
                </ul>
                <span class="navbar-text text-muted">
                    Manage your diabetes with ease
                </span>
            </div>
        </div>
    </nav>


    <!-- Messages -->
    <div class="container mt-3">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message|safe }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </div>

    <!-- Main content -->
    <main class="flex-grow-1 main-bg">
        <div class="container">
            {% block content %}{% endblock content %}
        </div>
    </main>

    <!-- Footer -->
    <footer class="footer">
        <div class="container text-center">
            <p class="m-0">
                {% block copyright %}Made by Gambit1583{% endblock copyright %}
            </p>
            <p class="m-0">
                Follow us:
                <a href="https://github.com/Gambit1583/Diabetes-App" class="text-white"><i class="fab fa-github-square ms-3"></i></a>
                <a href="#" class="text-white"><i class="fab fa-facebook-square ms-3"></i></a>
                <a href="#" class="text-white"><i class="fab fa-instagram-square ms-3"></i></a>
                <a href="https://github.com/users/Gambit1583/projects/6" class="text-white"><i class="fab fa-github-square ms-3"></i></a>
            </p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="{% static 'blog/js/voting.js' %}"></script>
</body>
</html>